---
appname: counter
category: counter
function:
- info: create counter
  params:
  - value: counter
  - value: create
  - value: counters
  - tips: counter_name
  - type: hash
    hash:
    - key: name
      value: counter_name
  return:
    type: json
    value:
    - name: status
      info: create result
    - name: value
      info: new counter value
- info: show all counters
  params:
  - value: counter
  - value: index
  - value: counters
  return:
    type: json
    value:
    - name: status
      info: index result
    - name: value
      info: all counter "key:value"
- info: show one counter
  params:
  - value: counter
  - value: show
  - value: counters
  - tips: counter_name
  return:
    type: json
    value:
    - name: status
      info: show result
    - name: value
      info: counter_name:value
- info: update counter
  params:
  - value: counter
  - value: update
  - value: counters
  - tips: counter_name
  return:
    type: json
    value:
    - name: status
      info: update result
    - name: value
      info: counter_name:new value
- info: delete counter
  params:
  - value: counter
  - value: delete
  - value: counters
  - tips: counter_name
  return:
    type: json
    value:
    - name: status
      info: delete result
    - name: info
      info: some info

